-- ============================================================================
-- CARA MEMBUAT ADMIN
-- ============================================================================
--
-- Ikuti 3 langkah berikut DI URUTAN ini:
--
-- LANGKAH 1: Buat user di Supabase Auth (Dashboard -> Authentication -> Users
--            -> Add User). Catat email yang digunakan, misalnya:
--            admin@bpjs-magang.test
--            password: <buat password kuat>
--
-- LANGKAH 2: Untuk database yang sudah menjalankan migration 0006, role admin
--            dibuat otomatis saat user Auth dibuat. Untuk database lama atau
--            untuk menjadikan user sebagai superadmin, jalankan query berikut:
--
INSERT INTO public.admin_roles (email, role) VALUES ('admin@bpjs-magang.test', 'superadmin');

-- LANGKAH 3: Login di portal admin (/login) dengan email & password tersebut.
--            Setelah login, Anda bisa mengelola semua data (peserta, absensi,
--            laporan, BPU, PU, dsb).
--
-- NOTE: Setelah migration 0006, setiap user Auth otomatis memiliki role admin.
--       User yang dibuat sebelum migration tersebut ikut diperbaiki melalui
--       backfill di migration. Role tetap dikontrol oleh tabel admin_roles.
-- ============================================================================
